server:
  port: 8762

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://47.114.177.174:9411
    sender:
      type: kafka
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 47.114.177.174:9092

eureka:
  client:
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/