server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/